export type Product = {
  id: string;
  name: string;
  weight: string;
  price: number;
  icon: string;
  category: string;
  brand: string;
  detail?: string;
  nutrition?: { calories: string; fat: string; sugar: string; protein: string };
};

export const ALL_PRODUCTS: Product[] = [
  // === FRUITS & VEGETABLES ===
  {
    id: "1",
    name: "Organic Broccoli",
    weight: "1kg",
    price: 4.99,
    icon: "🥦",
    category: "fruits",
    brand: "Kazi Farmas",
    detail: "Fresh organic broccoli, rich in vitamins and fiber.",
    nutrition: {
      calories: "34kcal",
      fat: "0.4g",
      sugar: "2g",
      protein: "2.8g",
    },
  },
  {
    id: "2",
    name: "Crimson Tomato",
    weight: "1kg",
    price: 4.99,
    icon: "🍅",
    category: "fruits",
    brand: "Kazi Farmas",
    detail: "Fresh crimson tomatoes, great for salads and cooking.",
    nutrition: {
      calories: "18kcal",
      fat: "0.2g",
      sugar: "2.6g",
      protein: "0.9g",
    },
  },
  {
    id: "5",
    name: "Bell Pepper",
    weight: "1kg",
    price: 3.99,
    icon: "🫑",
    category: "fruits",
    brand: "Kazi Farmas",
    detail: "Fresh bell peppers, rich in vitamins A and C.",
    nutrition: { calories: "31kcal", fat: "0.3g", sugar: "4g", protein: "1g" },
  },
  {
    id: "6",
    name: "Ginger",
    weight: "250g",
    price: 2.99,
    icon: "🫚",
    category: "fruits",
    brand: "Kazi Farmas",
    detail: "Fresh ginger root, great for cooking and health.",
    nutrition: {
      calories: "80kcal",
      fat: "0.8g",
      sugar: "1.7g",
      protein: "1.8g",
    },
  },
  {
    id: "f1",
    name: "Red Apple",
    weight: "1kg",
    price: 1.99,
    icon: "🍎",
    category: "fruits",
    brand: "Kazi Farmas",
    detail: "Fresh red apples.",
    nutrition: {
      calories: "52kcal",
      fat: "0.2g",
      sugar: "10g",
      protein: "0.3g",
    },
  },
  {
    id: "f3",
    name: "Organic Bananas",
    weight: "5kg",
    price: 3.0,
    icon: "🍌",
    category: "fruits",
    brand: "Kazi Farmas",
    detail: "Fresh organic bananas.",
    nutrition: {
      calories: "89kcal",
      fat: "0.3g",
      sugar: "12g",
      protein: "1.1g",
    },
  },
  {
    id: "fv1",
    name: "Carrot",
    weight: "1kg",
    price: 2.49,
    icon: "🥕",
    category: "fruits",
    brand: "Kazi Farmas",
    detail: "Fresh carrots, rich in beta-carotene.",
    nutrition: {
      calories: "41kcal",
      fat: "0.2g",
      sugar: "4.7g",
      protein: "0.9g",
    },
  },
  {
    id: "fv2",
    name: "Cucumber",
    weight: "500g",
    price: 1.49,
    icon: "🥒",
    category: "fruits",
    brand: "Kazi Farmas",
    detail: "Fresh cucumbers, great for salads.",
    nutrition: {
      calories: "16kcal",
      fat: "0.1g",
      sugar: "1.7g",
      protein: "0.7g",
    },
  },
  {
    id: "fv3",
    name: "Sweet Corn",
    weight: "3pcs",
    price: 2.99,
    icon: "🌽",
    category: "fruits",
    brand: "Kazi Farmas",
    detail: "Fresh sweet corn on the cob.",
    nutrition: {
      calories: "86kcal",
      fat: "1.2g",
      sugar: "6g",
      protein: "3.2g",
    },
  },
  {
    id: "fv4",
    name: "Watermelon",
    weight: "3kg",
    price: 5.49,
    icon: "🍉",
    category: "fruits",
    brand: "Kazi Farmas",
    detail: "Sweet and refreshing watermelon.",
    nutrition: {
      calories: "30kcal",
      fat: "0.2g",
      sugar: "6g",
      protein: "0.6g",
    },
  },
  {
    id: "fv5",
    name: "Mango",
    weight: "1kg",
    price: 3.99,
    icon: "🥭",
    category: "fruits",
    brand: "Kazi Farmas",
    detail: "Sweet tropical mangoes.",
    nutrition: {
      calories: "60kcal",
      fat: "0.4g",
      sugar: "14g",
      protein: "0.8g",
    },
  },
  {
    id: "fv6",
    name: "Strawberry",
    weight: "500g",
    price: 4.49,
    icon: "🍓",
    category: "fruits",
    brand: "Kazi Farmas",
    detail: "Fresh strawberries, rich in antioxidants.",
    nutrition: {
      calories: "32kcal",
      fat: "0.3g",
      sugar: "4.9g",
      protein: "0.7g",
    },
  },

  // === MEAT & FISH ===
  {
    id: "3",
    name: "Beef Bone",
    weight: "1kg",
    price: 5.99,
    icon: "🦴",
    category: "meat",
    brand: "Individual Collection",
    detail: "Fresh beef bone, great for soups and broths.",
    nutrition: { calories: "120kcal", fat: "8g", sugar: "0g", protein: "11g" },
  },
  {
    id: "4",
    name: "Broiler Chicken",
    weight: "1kg",
    price: 6.99,
    icon: "🍗",
    category: "meat",
    brand: "Individual Collection",
    detail: "Fresh broiler chicken, high in protein and low in fat.",
    nutrition: {
      calories: "165kcal",
      fat: "3.6g",
      sugar: "0g",
      protein: "31g",
    },
  },
  {
    id: "m1",
    name: "Beef Steak",
    weight: "500g",
    price: 9.99,
    icon: "🥩",
    category: "meat",
    brand: "Individual Collection",
    detail: "Premium beef steak, tender and juicy.",
    nutrition: { calories: "271kcal", fat: "17g", sugar: "0g", protein: "26g" },
  },
  {
    id: "m2",
    name: "Salmon Fillet",
    weight: "500g",
    price: 12.99,
    icon: "🐟",
    category: "meat",
    brand: "Individual Collection",
    detail: "Fresh Atlantic salmon fillet.",
    nutrition: { calories: "208kcal", fat: "13g", sugar: "0g", protein: "20g" },
  },
  {
    id: "m3",
    name: "Shrimp",
    weight: "500g",
    price: 10.99,
    icon: "🦐",
    category: "meat",
    brand: "Individual Collection",
    detail: "Fresh shrimp, great for stir-fry.",
    nutrition: { calories: "99kcal", fat: "0.3g", sugar: "0g", protein: "24g" },
  },
  {
    id: "m4",
    name: "Pork Ribs",
    weight: "1kg",
    price: 8.99,
    icon: "🍖",
    category: "meat",
    brand: "Individual Collection",
    detail: "Fresh pork ribs for grilling or braising.",
    nutrition: { calories: "297kcal", fat: "20g", sugar: "0g", protein: "26g" },
  },
  {
    id: "m5",
    name: "Duck",
    weight: "1.5kg",
    price: 11.99,
    icon: "🦆",
    category: "meat",
    brand: "Individual Collection",
    detail: "Whole fresh duck.",
    nutrition: { calories: "337kcal", fat: "28g", sugar: "0g", protein: "19g" },
  },

  // === DAIRY & EGGS ===
  {
    id: "7",
    name: "Egg Chicken",
    weight: "4pcs",
    price: 1.99,
    icon: "🥚",
    category: "dairy",
    brand: "Kazi Farmas",
    detail: "Fresh eggs, rich in protein and vitamins.",
    nutrition: { calories: "78kcal", fat: "5g", sugar: "0g", protein: "6g" },
  },
  {
    id: "f2",
    name: "Egg Chicken White",
    weight: "180g",
    price: 1.5,
    icon: "🥚",
    category: "dairy",
    brand: "Kazi Farmas",
    detail: "Fresh white eggs.",
    nutrition: { calories: "78kcal", fat: "5g", sugar: "0g", protein: "6g" },
  },
  {
    id: "d1",
    name: "Fresh Milk",
    weight: "1L",
    price: 1.99,
    icon: "🥛",
    category: "dairy",
    brand: "Kazi Farmas",
    detail: "Fresh full cream milk.",
    nutrition: {
      calories: "61kcal",
      fat: "3.3g",
      sugar: "4.8g",
      protein: "3.2g",
    },
  },
  {
    id: "d2",
    name: "Butter",
    weight: "250g",
    price: 3.5,
    icon: "🧈",
    category: "dairy",
    brand: "Kazi Farmas",
    detail: "Creamy unsalted butter.",
    nutrition: {
      calories: "717kcal",
      fat: "81g",
      sugar: "0g",
      protein: "0.9g",
    },
  },
  {
    id: "d3",
    name: "Eggs Duck",
    weight: "12pcs",
    price: 2.99,
    icon: "🥚",
    category: "dairy",
    brand: "Kazi Farmas",
    detail: "Fresh farm eggs.",
    nutrition: { calories: "78kcal", fat: "5g", sugar: "0g", protein: "6g" },
  },
  {
    id: "d4",
    name: "Yogurt",
    weight: "500g",
    price: 2.49,
    icon: "🫙",
    category: "dairy",
    brand: "Kazi Farmas",
    detail: "Creamy plain yogurt.",
    nutrition: {
      calories: "59kcal",
      fat: "3.3g",
      sugar: "4g",
      protein: "3.5g",
    },
  },
  {
    id: "d5",
    name: "Cheddar Cheese",
    weight: "200g",
    price: 4.99,
    icon: "🧀",
    category: "dairy",
    brand: "Kazi Farmas",
    detail: "Sharp cheddar cheese.",
    nutrition: {
      calories: "403kcal",
      fat: "33g",
      sugar: "0.1g",
      protein: "25g",
    },
  },
  {
    id: "d6",
    name: "Cream Cheese",
    weight: "250g",
    price: 3.99,
    icon: "🧀",
    category: "dairy",
    brand: "Kazi Farmas",
    detail: "Smooth and creamy cream cheese.",
    nutrition: { calories: "342kcal", fat: "34g", sugar: "3g", protein: "6g" },
  },

  // === BEVERAGES ===
  {
    id: "b1",
    name: "Diet Coke",
    weight: "335ml",
    price: 1.99,
    icon: "🥤",
    category: "beverages",
    brand: "Cocola",
    detail: "Refreshing diet cola with zero sugar.",
    nutrition: { calories: "1kcal", fat: "0g", sugar: "0g", protein: "0g" },
  },
  {
    id: "b2",
    name: "Sprite Can",
    weight: "325ml",
    price: 1.5,
    icon: "🧃",
    category: "beverages",
    brand: "Cocola",
    detail: "Crisp and refreshing lemon-lime soda.",
    nutrition: { calories: "140kcal", fat: "0g", sugar: "38g", protein: "0g" },
  },
  {
    id: "b3",
    name: "Apple & Grape Juice",
    weight: "2L",
    price: 15.99,
    icon: "🍹",
    category: "beverages",
    brand: "Ifad",
    detail: "Fresh apple and grape juice blend.",
    nutrition: { calories: "120kcal", fat: "0g", sugar: "28g", protein: "0g" },
  },
  {
    id: "b4",
    name: "Orange Juice",
    weight: "2L",
    price: 15.99,
    icon: "🍊",
    category: "beverages",
    brand: "Ifad",
    detail: "Freshly squeezed orange juice.",
    nutrition: { calories: "112kcal", fat: "0g", sugar: "26g", protein: "2g" },
  },
  {
    id: "b5",
    name: "Coca Cola Can",
    weight: "325ml",
    price: 4.99,
    icon: "🥤",
    category: "beverages",
    brand: "Cocola",
    detail: "Classic Coca Cola.",
    nutrition: { calories: "139kcal", fat: "0g", sugar: "35g", protein: "0g" },
  },
  {
    id: "b6",
    name: "Pepsi Can",
    weight: "330ml",
    price: 4.99,
    icon: "🥤",
    category: "beverages",
    brand: "Cocola",
    detail: "Classic Pepsi cola.",
    nutrition: { calories: "150kcal", fat: "0g", sugar: "41g", protein: "0g" },
  },
  {
    id: "bv1",
    name: "Green Tea",
    weight: "500ml",
    price: 2.49,
    icon: "🍵",
    category: "beverages",
    brand: "Ifad",
    detail: "Refreshing green tea.",
    nutrition: { calories: "2kcal", fat: "0g", sugar: "0g", protein: "0g" },
  },
  {
    id: "bv2",
    name: "Mineral Water",
    weight: "1.5L",
    price: 0.99,
    icon: "💧",
    category: "beverages",
    brand: "Ifad",
    detail: "Pure natural mineral water.",
    nutrition: { calories: "0kcal", fat: "0g", sugar: "0g", protein: "0g" },
  },
  {
    id: "bv3",
    name: "Mango Juice",
    weight: "1L",
    price: 3.49,
    icon: "🥭",
    category: "beverages",
    brand: "Ifad",
    detail: "Fresh mango juice.",
    nutrition: { calories: "130kcal", fat: "0g", sugar: "30g", protein: "1g" },
  },
  {
    id: "bv4",
    name: "Milk Tea",
    weight: "330ml",
    price: 2.99,
    icon: "🧋",
    category: "beverages",
    brand: "Cocola",
    detail: "Creamy milk tea.",
    nutrition: { calories: "150kcal", fat: "3g", sugar: "20g", protein: "3g" },
  },

  // === BAKERY & SNACKS ===
  {
    id: "bk1",
    name: "White Bread",
    weight: "400g",
    price: 2.5,
    icon: "🍞",
    category: "bakery",
    brand: "Ifad",
    detail: "Soft and fresh white bread.",
    nutrition: { calories: "265kcal", fat: "3.2g", sugar: "5g", protein: "9g" },
  },
  {
    id: "bk2",
    name: "Croissant",
    weight: "200g",
    price: 3.99,
    icon: "🥐",
    category: "bakery",
    brand: "Ifad",
    detail: "Buttery and flaky croissant.",
    nutrition: { calories: "406kcal", fat: "21g", sugar: "11g", protein: "8g" },
  },
  {
    id: "bk3",
    name: "Chocolate Cake",
    weight: "500g",
    price: 7.99,
    icon: "🎂",
    category: "bakery",
    brand: "Ifad",
    detail: "Rich chocolate layer cake.",
    nutrition: { calories: "371kcal", fat: "15g", sugar: "45g", protein: "5g" },
  },
  {
    id: "bk4",
    name: "Potato Chips",
    weight: "150g",
    price: 2.29,
    icon: "🥔",
    category: "bakery",
    brand: "Cocola",
    detail: "Crispy salted potato chips.",
    nutrition: {
      calories: "536kcal",
      fat: "35g",
      sugar: "0.5g",
      protein: "7g",
    },
  },
  {
    id: "bk5",
    name: "Cookies",
    weight: "200g",
    price: 3.49,
    icon: "🍪",
    category: "bakery",
    brand: "Ifad",
    detail: "Crunchy chocolate chip cookies.",
    nutrition: { calories: "502kcal", fat: "24g", sugar: "36g", protein: "6g" },
  },
  {
    id: "bk6",
    name: "Muffin",
    weight: "4pcs",
    price: 4.49,
    icon: "🧁",
    category: "bakery",
    brand: "Ifad",
    detail: "Soft blueberry muffins.",
    nutrition: { calories: "377kcal", fat: "14g", sugar: "30g", protein: "5g" },
  },

  // === COOKING OIL ===
  {
    id: "o1",
    name: "Olive Oil",
    weight: "1L",
    price: 8.99,
    icon: "🫒",
    category: "oil",
    brand: "Ifad",
    detail: "Premium extra virgin olive oil.",
    nutrition: { calories: "884kcal", fat: "100g", sugar: "0g", protein: "0g" },
  },
  {
    id: "o2",
    name: "Sunflower Oil",
    weight: "2L",
    price: 5.99,
    icon: "🌻",
    category: "oil",
    brand: "Ifad",
    detail: "Pure sunflower cooking oil.",
    nutrition: { calories: "884kcal", fat: "100g", sugar: "0g", protein: "0g" },
  },
  {
    id: "o3",
    name: "Coconut Oil",
    weight: "500ml",
    price: 6.99,
    icon: "🥥",
    category: "oil",
    brand: "Ifad",
    detail: "Pure cold-pressed coconut oil.",
    nutrition: { calories: "862kcal", fat: "100g", sugar: "0g", protein: "0g" },
  },
  {
    id: "o4",
    name: "Canola Oil",
    weight: "2L",
    price: 4.99,
    icon: "🛢️",
    category: "oil",
    brand: "Ifad",
    detail: "Light canola cooking oil.",
    nutrition: { calories: "884kcal", fat: "100g", sugar: "0g", protein: "0g" },
  },

  // === PULSES ===
  {
    id: "p1",
    name: "Red Lentils",
    weight: "1kg",
    price: 2.99,
    icon: "🫘",
    category: "pulses",
    brand: "Ifad",
    detail: "Dried red lentils, high in protein.",
    nutrition: { calories: "352kcal", fat: "1g", sugar: "2g", protein: "25g" },
  },
  {
    id: "p2",
    name: "Chickpeas",
    weight: "1kg",
    price: 3.49,
    icon: "🫘",
    category: "pulses",
    brand: "Ifad",
    detail: "Dried chickpeas, great for curries.",
    nutrition: { calories: "364kcal", fat: "6g", sugar: "11g", protein: "19g" },
  },
  {
    id: "p3",
    name: "Black Beans",
    weight: "500g",
    price: 2.49,
    icon: "🫘",
    category: "pulses",
    brand: "Ifad",
    detail: "Dried black beans.",
    nutrition: {
      calories: "341kcal",
      fat: "1.4g",
      sugar: "0.3g",
      protein: "22g",
    },
  },
  {
    id: "p4",
    name: "Green Peas",
    weight: "500g",
    price: 1.99,
    icon: "🟢",
    category: "pulses",
    brand: "Ifad",
    detail: "Dried green peas.",
    nutrition: {
      calories: "339kcal",
      fat: "1.1g",
      sugar: "6g",
      protein: "24g",
    },
  },

  // === RICE ===
  {
    id: "r1",
    name: "Basmati Rice",
    weight: "2kg",
    price: 5.99,
    icon: "🍚",
    category: "rice",
    brand: "Individual Collection",
    detail: "Premium basmati rice.",
    nutrition: { calories: "360kcal", fat: "0.9g", sugar: "0g", protein: "7g" },
  },
  {
    id: "r2",
    name: "Jasmine Rice",
    weight: "2kg",
    price: 4.99,
    icon: "🍚",
    category: "rice",
    brand: "Individual Collection",
    detail: "Fragrant jasmine rice.",
    nutrition: { calories: "356kcal", fat: "0.6g", sugar: "0g", protein: "7g" },
  },
  {
    id: "r3",
    name: "Brown Rice",
    weight: "2kg",
    price: 5.49,
    icon: "🍚",
    category: "rice",
    brand: "Individual Collection",
    detail: "Healthy whole grain brown rice.",
    nutrition: { calories: "370kcal", fat: "2.9g", sugar: "0g", protein: "8g" },
  },
  {
    id: "r4",
    name: "Sticky Rice",
    weight: "1kg",
    price: 3.99,
    icon: "🍙",
    category: "rice",
    brand: "Individual Collection",
    detail: "Glutinous sticky rice.",
    nutrition: { calories: "370kcal", fat: "0.6g", sugar: "0g", protein: "7g" },
  },
];

export const PRODUCTS_MAP: Record<string, Product> = Object.fromEntries(
  ALL_PRODUCTS.map((p) => [p.id, p]),
);
